### ISSUE TITLE
[issue] 3249 segmentation fault (core dumped)

### ISSUE THREAD

**Issue by balejos** [pavlobu/deskreen#121]
Hi,

I'm running deskreen on a x64 Archlinux and after a few seconds I get a `3249 segmentation fault (core dumped)  deskreen` which closes deskreen. Could you, please, help me with it?

Thanks!

**Comment by pavlobu** [comment]
Hi I don't have archlinux on my mac and I'm collecting funds on opencollective to buy a windows + linux pc that I can develop on. Because mostly I develop on mac, I  don't have hardware resources for now to fix those problems that you have. 

Other archlinux users haven't reported that issue.

Try downloading Appimage from website or compile it yourself following documentation guides

Cheers,
Paul
