### ISSUE TITLE
"No WiFi and LAN connection." on Windows 11

### ISSUE THREAD

**Issue by flug8** [pavlobu/deskreen#176]
IF I open Deskreen on Win11 i get a popup "No WiFi and LAN connection.". But if i connect to my local ip + port it shows me that i can connect to deskreen but now i have the problem that i cant accept the connection, because this popup is over it. Is there a way to remove this wrong "No WiFi and LAN connection."-popup?
![image](https://user-images.githubusercontent.com/80972789/147092241-cad8fbf4-cf00-40db-b919-81fb9d1027da.png)

**Comment by kilzone** [comment]
Same as: https://github.com/pavlobu/deskreen/issues/172#issuecomment-1017147018

**Comment by kilzone** [comment]
I'm not sure which version of Deskreen the issues first occured in and how many releases since, but the issue back then was the removal of WMIC (Windows Management Instrumentation Command-line) in Windows 11 (Microsoft moved to Powershell variant). If it is still needed, back then I created this repository: https://github.com/kilzone/wmic-windows-11

This contains a version of WMIC that can be copied into your Windows folder and solved the issue above. However, no guarantees that it will keep working in the future (or maybe even works, since I solved the issue in 2022 and moved on to other solutions since).
