### ISSUE TITLE
High CPU usage.

### ISSUE THREAD

**Issue by linchangyi** [pavlobu/deskreen#31]
Perfromance is great,  but cpu usage is too high.

**Comment by linchangyi** [comment]
cpu usage before sharing screen
![image](https://user-images.githubusercontent.com/6831676/105394822-03c4b580-5c59-11eb-9cc1-330fca507688.png)
cpu usage while sharing screen
![image](https://user-images.githubusercontent.com/6831676/105395054-48e8e780-5c59-11eb-8258-9fa248e57df2.png)

**Comment by pavlobu** [comment]
Hi thank you for submitting this issue.

It's normal that it uses high cpu because there is no 'magic' behind it. 
Deskreen requires RAM and CPU resources to run. It uses WebRTC under the hood so it is is the
main bottleneck and will remain for a long time in Deskreen.
But even if we go to implement other than WebRTC screen sharing solution I'm afraid we would not
save that much of CPU, so going so long through the process of developing such an improvement is
not likely worth it.
Besides Deskreen runs on electron.js which is basically a chrome browser and it eats a lot of resources.
But for electron things may change in the future and they are working on optimization a lot. And their
community much much larger than Deskreen one.

Cheers,
Paul

**Comment by pavlobu** [comment]
So I will close it at the moment because it is difficult to solve at the moment. But let's keep it in mind that we need to be thinking on how to reduce cpu usage.
I will be updating documentation soon so we can discuss.

**Comment by MarkoSchuetz** [comment]
I understand that it has to use the resources of the computer on which it runs. But I'm under the impression that it uses more CPU power than e.g. when I have OBS running to compose a scene with easyeffects for audio noise reduction and I stream this into a running Google Meet and that seems counter-intuitive.
