### ISSUE TITLE
Could this be packaged into the AUR?

### ISSUE THREAD

**Issue by CardboardTurtle** [pavlobu/deskreen#41]

**Comment by sonuishaq67** [comment]
@CardboardTurtle 
I made the pkgbuild 
Ill try to make it live by 7AM UTC

**Comment by Tragyn** [comment]
> ~@CardboardTurtle~
> ~I made the pkgbuild~
> ~Ill try to make it live by 7AM UTC~
> 
> Looks like someone else already [made it](https://aur.archlinux.org/packages/deskreen/)

This package doesn't seem to install.  At least, not for me:

`error: failed to parse srcinfo for 'deskreen-1.0.0-1': key 'groups' requires a value: Line 9: groups =`

**Comment by sonuishaq67** [comment]
yeah try [my pkgbuild](https://github.com/sonuishaq67/packages/tree/master/deskreen-proposed) until the maintainer corrects it

**Comment by sonuishaq67** [comment]
I adopted the package and pushed the [right version](https://aur.archlinux.org/packages/deskreen/)
I think its safe to close this issue.

**Comment by Archaeoraptor** [comment]
> yeah try [my pkgbuild](https://github.com/sonuishaq67/packages/tree/master/deskreen-proposed) until the maintainer corrects it

I am sorry, seems my PKGBUILD using deb has some problems, I orphaned it and transftered this aur package to you. To use the appimage is a better idea.

**Comment by pavlobu** [comment]
Hey guys, can you share here how to build and publish aur package in command line ?
I will be adding this auto build and publish step into releases pipeline.

Thanks,
Paul

**Comment by BMicraft** [comment]
> Hey guys, can you share here how to build and publish aur package in command line ?
> I will be adding this auto build and publish step into releases pipeline.

IF you have access to a working instance of arch linux you just need to install the `base-devel` group by doing `pacman -S base-devel`. Then you can just place the `PKGBUILD` file in your current working dir and run [`makepkg`](https://wiki.archlinux.org/index.php/Makepkg).
I am not sure how the process of installing `makepkg` would look like on your distribution but the wiki mentions that it should run on any "build-capable Unix platform".

The entire process of creating a package is detailed in [this excellent article](https://wiki.archlinux.org/index.php/Creating_packages).

**Comment by sonuishaq67** [comment]
> Hey guys, can you share here how to build and publish aur package in command line ?
> I will be adding this auto build and publish step into releases pipeline.
@pavlobu 

Here's everything you need to know about [PKGBUILDS](https://wiki.archlinux.org/index.php/PKGBUILD) and the link above mine

and the [submission guidelines](https://wiki.archlinux.org/index.php/AUR_submission_guidelines)

you'll need a [aur account](https://aur.archlinux.org/register/) too 

I'm currently the maintainer of this package in AUR if you [mail me](mailto:sonuishaq67@gmail.com) with your username I'll give co-maintainer or disown the package so you can adopt it, based on your needs

**Comment by Archaeoraptor** [comment]
Now the AUR package `deskreen` just use Appimage in the release since Archlinux' format is not supplyed in the release now. 

Electron has a build options `pacman` for Archlinux to build package for archlinux user in `tar.xz` format, see here: [electron build: Any Linux Target](https://www.electron.build/configuration/linux). A package for arch can be generated by add a target in `package.json`

```json
"linux": {
  "target": [
    "deb",
    "rpm",
    "pacman",
    "AppImage"
  ],
```

I guess some thing may also be changed in github action in the next release if you want to use Github Action as CI to publish a release.

To upload the release to AUR in cli, here is a cli tools: [aurpublish](https://github.com/eli-schwartz/aurpublish)(https://github.com/eli-schwartz/aurpublish)  (It works well on Arch, I am not sure if it will work on Github Action with Ubuntu 18.04, if it not work, use [Archlinux Enviroments](https://github.com/zaoqi/github-actions-archlinux) in Github Action maybe helpful)

I am not the maintianer of AUR package deskreen now and I don’t have the access, so just contact sonuishaq67. 

A Github Action Example is here: [Arch Linux PKGBUILD builder action](https://github.com/marketplace/actions/arch-linux-pkgbuild-builder-action)

Or if you want to build a electron application using PKGBUILD from source code (this will build this application in user's PC from source code) in Arch way rather than using Github Actions, PKGBIULD should write like this [ArchWiki: Electron package guidelines](https://wiki.archlinux.org/index.php/Electron_package_guidelines)

(AUR' guidline encourage people to build from source code rather than download a binary release while many package don't do in this way)

**Comment by pavlobu** [comment]
wow! 
great! thank you all for sharing it here. 
I'll be thinking on how to put it into build pipeline on [Github release workflow](https://github.com/pavlobu/deskreen/blob/master/.github/workflows/release.yml) then. Or if you know how to do it, you can submit your updated release workflow in PR.

Cheers,
Paul

**Comment by sonuishaq67** [comment]
@pavlobu lemme confirm once again 
you want to update pkgbuilds in aur automatically when a build is released right?

**Comment by pavlobu** [comment]
correct, it should be automated process. otherwise it will not be the latest version all the time and it is tedious and boring manual process if it is not automated

**Comment by sonuishaq67** [comment]
Okay so i made a [script for publishing](https://pastebin.ubuntu.com/p/8j95bQHDf6/)
idk much about CI/CD .

It basically generates sha256sums and updates the package name 
you have to set 4 variables email, name, private_key(constant so can be a secret) and version

**Comment by pavlobu** [comment]
@sonuishaq67 thanks that is super useful! Yes I can add secret to Github Workflow and they allow to store secrets there. I'll try this as soon as I get chance!

**Comment by pavlobu** [comment]
@sonuishaq67 Hi, with a great help from @VergeDX https://github.com/pavlobu/deskreen/pull/101
We have added a separate github workflow that is triggered when new release happened. 
we can be adding more jobs in this workflow file like publishing AUR package there.
If you have a time and want to help, your PR is welcome.

**Comment by sonuishaq67** [comment]
Sure I'll start working on it @pavlobu

**Comment by sonuishaq67** [comment]
sorry for the delay but it looks like pacman has a [issue](https://www.reddit.com/r/archlinux/comments/lek2ba/arch_linux_on_docker_ci_could_not_find_or_read/) on docker images right now 

I wanted to use arch linux container because it contains makepkg so you can test for building and also for --printsrcinfo which is essential for aur packages 
until its resolved I'll be manually updating the aur

**Comment by pavlobu** [comment]
Hi, you mean you followed this?
https://docs.github.com/en/actions/guides/about-service-containers

I’m sure we can use official arch linux container in github workflows as an environment

**Comment by sonuishaq67** [comment]
Theres a workaround for that and its successfully passing in my test repo

However I had a doubt If __ were

**Comment by pavlobu** [comment]
@sonuishaq67 
Hi, sounds good.
You can put your packaging job here:
https://github.com/pavlobu/deskreen/blob/master/.github/workflows/post-release-publish.yml

Right after "homebrew-pr" job, just call it something related to procedure.
Also you can change runs-on to something like ubuntu-latest or other os that works for your script.

**Comment by sonuishaq67** [comment]
> runs-on to something like ubuntu-latest
@pavlobu That's for CI
I was talking about a .sh script

**Comment by pavlobu** [comment]
Ok you can trigger your script in a new aur script on ubuntu.
And yes there is no place on a project path for these kind of scripts.
I think you can create a new `scripts/ci` in the root of project and put your script there.
Sounds good?

**Comment by sonuishaq67** [comment]
Hey @pavlobu I sent a pr 
you'll have to set `private_key` `email` `name` secrets 

`private_key` is the key you'll have to generate from creating a aur account from [before comment](https://github.com/pavlobu/deskreen/issues/41#issuecomment-768016906) after creating an account please give me your username so that I can give you repository access in aur

`email` and `name` for pushing to git

**Comment by pavlobu** [comment]
Hi thank you! I have created an account on AUR it is: pavlobu
Minor thing to change:
Can you pls rename secrets in yml by adding AUR suffix or prefix and also capitalize them? 
AUR suffix or prefix will distinguish those secrets from other secrets with the same purpose.
As it is how other secrets are named currently, let's follow that rule

Thanks again,
Paul

**Comment by sonuishaq67** [comment]
yep sure will do it now

**Comment by sonuishaq67** [comment]
@pavlobu done !

**Comment by pavlobu** [comment]
@sonuishaq67 Thank you very much! Merged https://github.com/pavlobu/deskreen/commit/055a77e2c4e78ac50fb335595f8032420b528360
Now we can close this issue I think :)

**Comment by pavlobu** [comment]
@sonuishaq67 Hi, I created 1.0.6 release and some stuff was failed during aur packaging workflow:

https://github.com/pavlobu/deskreen/runs/1942855629?check_suite_focus=true#step:3:77

Do you know what is wrong?

**Comment by sonuishaq67** [comment]
> error: failed to initialize alpm library
(could not find or read directory: /var/lib/pacman/)


looks like the glibc problem from before lemme see if I can do anything

**Comment by sonuishaq67** [comment]
@pavlobu  Looks like the [earlier hack](https://github.com/pavlobu/deskreen/blob/1a6c881041e753b16e1055cfa62b9806fb475552/.github/workflows/post-release-publish.yml#L41) is also not working anymore

**Comment by sonuishaq67** [comment]
For now I pushed 1.0.6 to aur 
I have my final exams from tomorrow so I'll be little busy
If someone could find a workaround it'd be good or else I'll try doing it tomorrow evening
