### ISSUE TITLE
Teleprompter mode

### ISSUE THREAD

**Issue by tobi** [pavlobu/deskreen#93]
Great tool. Would love to be able to use it with mirrored screen option. This would be very popular with the people who run teleprompters.

**Comment by pavlobu** [comment]
Hi, thank you for liking and using Deskreen. Deskreen has already this feature for mirroring screen. Please for such occasions post in our discussions, using already existing discussions for that.

**Comment by pavlobu** [comment]
if you didn't read a template of enhancement label in issues, here is a quick reminder:


# Here you post only concrete examples of enhancements with code and solutions that you have. Other BIG enhancements and general ideas of features you would like to see in Deskreen, you post here: https://github.com/pavlobu/deskreen/discussions/50

# Otherwise this issue will be closed.

**Comment by pavlobu** [comment]
Ok I got what you mean. @ericsmalling  also mentioned same feature and here is my reply:
https://github.com/pavlobu/deskreen/discussions/48#discussioncomment-336176

please lets continue this discussion here: https://github.com/pavlobu/deskreen/discussions/48

**Comment by pavlobu** [comment]
added in v1.0.4 🎉
